###
GRPC localhost:1234/viot.FEngineExecutor/Execute

{
  "attributes": [
    {"name": "s", "str": "s_vl"},
    {"name": "i", "i32": 100}
  ],
  "function": {
    "input": [
      {"name": "s", "str": "hello"},
      {"name": "i", "i32": 123}
    ],
    "output": [
      {"name": "s", "type": "String"},
      {"name": "i", "type": "Int32"}
    ],
    "code": "me.test({s, i});\nTable('a').Select({'and':[{'a':{'$gt':10}}]});\nreturn {i:i+me.i, s:s+me.s}"
  },
  "referee": {
    "test": {
      "input": [
        {"name": "str", "type": "String"},
        {"name": "i32", "type": "Int32"}
      ],
      "output": [
        {"name": "str", "type": "String"},
        {"name": "i32", "type": "Int32"}
      ],
      "code": "return {i32: i32+1, str: str+'!'}"
    }
  }
}
