###
GRPC localhost:1234/viot.FEngineExecutor/Execute

{
  "attributes": [
    {"name": "s", "str": "s_vl"},
    {"name": "i", "i32": 100}
  ],
  "function": {
    "input": [
      {"name": "s", "str": "hello"},
      {"name": "i", "i32": 123}
    ],
    "output": [
      {"name": "s"}
    ],
    "code": "me.test({s,i});\nTable('a').Select({and:[{a:{$gt:10,$lt:20}}]});\nme.i=0;\nreturn {i:i+me.i, s:s+me.s}"
  },
  "referee": {
    "test": {
      "input": [
        {"name": "str"},
        {"name": "i32"}
      ],
      "output": [
        {"name": "str"},
        {"name": "i32"}
      ],
      "code": "return {i32: i32+1, str: str+'!'}"
    }
  }
}
