###
GET {{host}}/fe/thing/{{thing}}/service

###
POST {{host}}/fe/thing/{{thing}}
Content-Type: application/json

{
  "services": {
    "test": {
      "input": [
        {"name": "s", "type": "string"},
        {"name": "i", "type": "i32"}
      ],
      "output": "json",
      "code": "return {sum: s + i}"
    }
  }
}
###
GET {{host}}/fe/thing/{{thing}}/service/templ_method

###
POST {{host}}/fe/thing/{{thing}}/service/templ_method
Content-Type: application/json
Accept: application/json

{
  "i": 100,
  "s": "one long string"
}

###
POST {{host}}/fe/condition
Content-Type: application/json
Accept: application/json

{
  "$and": [
    {"id": {"$in": [1, 1.1, 2, 3, 4]}},
    {
      "$and": [
        {"id": {"$nin": [1.1, 2, 3, 4]}},
        {
          "$or": [
            {"trigger_time": {"$ge": "01:23:45", "$le": "12:34:56"}},
            {"trigger_date": {"$ge": "2020-08-19", "$le": "2020-09-02"}}
          ]
        },
        {"available": true}
      ]
    },
    {
      "$or": [
        {"name": {"$find": "summer sale"}},
        {"name": {"$match": "+summer -sale +(>vacation <firework)"}}
      ]
    }
  ]
}
