###
POST {{host}}/fe/thing/

###
POST {{host}}/fe/exec
Content-Type: application/json
Accept: application/json

{
  "attributes": [
    {"name": "s", "type": "String", "value": "s_vl"},
    {"name": "i", "type": "Int32", "value": 100}
  ],
  "function": {
    "input": [
      {"name": "s", "type": "String", "value": "hello"},
      {"name": "i", "type": "Int32", "value": 123}
    ],
    "output": [
      {"name": "s"}
    ],
    "code": "me.test({s,i});\nTable('a').Select({and:[{a:{$gt:10,$lt:20}}]});\nme.i=0;\nreturn {i:i+me.i, s:s+me.s}"
  },
  "referee": {
    "test": {
      "input": [
        {"name": "str", "type": "String"},
        {"name": "i32", "type": "Int32"}
      ],
      "output": [
        {"name": "str"},
        {"name": "i32"}
      ],
      "code": "return {i32: i32+1, str: str+'!'}"
    }
  }
}

###
POST {{host}}/fe/condition
Content-Type: application/json
Accept: application/json

{
  "$and": [
    {"id": {"$in": [1, 1.1, 2, 3, 4]}},
    {
      "$and": [
        {"id": {"$nin": [1.1, 2, 3, 4]}},
        {
          "$or": [
            {"trigger_time": {"$ge": "01:23:45", "$le": "12:34:56"}},
            {"trigger_date": {"$ge": "2020-08-19", "$le": "2020-09-02"}}
          ]
        },
        {"available": true}
      ]
    },
    {
      "$or": [
        {"name": {"$find": "summer sale"}},
        {"name": {"$match": "+summer -sale +(>vacation <firework)"}}
      ]
    }
  ]
}
