services:
  timescale:
    container_name: timescale
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_PASSWORD=1
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 5432:5432
    volumes:
      - ~/data/timescale:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: redis
    image: redis
