services:
  timescale:
    container_name: timescale
    image: timescale/timescaledb:latest-pg12
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_PASSWORD=1
    ports:
      - 5432:5432
    volumes:
      - ~/data/timescale:/var/lib/postgresql/data
    restart: unless-stopped
  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: users_business_events
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: F-QFQpmCL9UkR3qyoXnLkzWj03s6m4eCvYgDl1ePfHBf9ph7yxaSgQ6WN0i9giNgRTfONwVMK1f977r_g71oNQ==
    ports:
      - "8086:8086"
  redis:
    container_name: redis
    image: redis:6-alpine
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    restart: unless-stopped
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.33
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    restart: unless-stopped
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 9090:9090
    restart: unless-stopped
volumes:
  cache:
    driver: local
